#ifndef __WRSOCcontrtolWRSOCcontrolPanelSet__
#define __WRSOCcontrtolWRSOCcontrolPanelSet__

/**
@file
Subclass of WRSOCcontrolPanelSet, which is generated by wxFormBuilder.
*/

#include "WRSOCcontrtol_gui.h"

//// end generated include

/** Implementing WRSOCcontrolPanelSet */
class WRSOCcontrtolWRSOCcontrolPanelSet : public WRSOCcontrolPanelSet
{
	public:
		/** Constructor */
		WRSOCcontrtolWRSOCcontrolPanelSet( wxWindow* parent );
	//// end generated class members
	
};

#endif // __WRSOCcontrtolWRSOCcontrolPanelSet__
