#ifndef __WRSOCcontrtolWRSOCcontrtolPanelSet__
#define __WRSOCcontrtolWRSOCcontrtolPanelSet__

/**
@file
Subclass of WRSOCcontrolPanelSet, which is generated by wxFormBuilder.
*/

#include "WRSOCcontrtol_gui.h"

//// end generated include

/** Implementing WRSOCcontrolPanelSet */
class WRSOCcontrtolWRSOCcontrtolPanelSet : public WRSOCcontrolPanelSet
{
	public:
		/** Constructor */
		WRSOCcontrtolWRSOCcontrtolPanelSet( wxWindow* parent );
	//// end generated class members
	
};

#endif // __WRSOCcontrtolWRSOCcontrtolPanelSet__
