#ifndef __WRSOCcontrtolWRSOCContrtolPackPanel__
#define __WRSOCcontrtolWRSOCContrtolPackPanel__

/**
@file
Subclass of WRSOCContrtolPackPanel, which is generated by wxFormBuilder.
*/

#include "WRSOCcontrtol_gui.h"

//// end generated include

/** Implementing WRSOCContrtolPackPanel */
class WRSOCcontrtolWRSOCContrtolPackPanel : public WRSOCContrtolPackPanel
{
	public:
		/** Constructor */
		WRSOCcontrtolWRSOCContrtolPackPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __WRSOCcontrtolWRSOCContrtolPackPanel__
